- name: ITEA
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Install python3
      yum:
        name: python3
        state: latest   

    - name: Install docker pip
      pip:
        name: docker