- name: ITEA
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install python3
      yum:
        name: python3
        state: latest   

